### PR TITLE
fix size and md5sum of baybridge.jpg

### PR DESCRIPTION
**Pull request by shogo82148**
baybridge.jpg is resized by following commit.
https://github.com/plack/Plack/commit/6e922637a3da50fe4a20f03d4f1be134a98cc4e6

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.  It is great to know that the tests are failing with the recent versions of Plack.  However, if we apply the change, the tests would start failing when run with older versions of Plack.

Would you mind changing the PR to do the following?
* bundle baybridge.jpg to Starlet
* use the bundled file in the test

**Comment by shogo82148** [comment]
Thank you for reviewing. I will.

**Comment by kazuho** [comment]
@shogo82148 I am sorry but I did it myself.

I needed to publish Starlet 0.25 which is mandatory for https://github.com/h2o/h2o/pull/383 getting merged, and wanted to have the fix for this issue included in the release.

**Comment by shogo82148** [comment]
@kazuho Sorry for my late reply... Thank you!

**Pull request closed without merging**
